### ISSUE TITLE
Problem with nullable parsers

### ISSUE THREAD

**Issue by Netmosfera** [qntm/loco#15]
I apologize the poor title but that's all I got right now.

https://github.com/qntm/loco/blob/master/src/Loco.php#L795

I believe this line is wrong, it should be:

```
            if (!is_a($internal, "Ferno\\Loco\\GreedyMultiParser")) {
```

Also, I'm not sure what "$internal->optional" is, probably is meant to be nullable?

**Comment by qntm** [comment]
Can you provide an example of PHP code which is failing due to this?
