### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by mindplay-dk** [qntm/loco#8]
In order for this project to gain some footing, you need to provide a license - most developers are working in a commercial setting of some sort, and won't consider contributing unless the code is properly licensed.

**Comment by jchook** [comment]
Hey @qntm, really impressed with your work on loco.

I agree with mindplay-dk. You need a License, preferably a permissive one such as MIT. Text parsing seems pretty fundamental to most applications you would write in PHP. Ideally folks would get on board here and avoid writing their own (bad) parsers.

I haven't seen any PHP bindings for [tree-sitter](https://github.com/tree-sitter/tree-sitter) or similar, though. Am I missing something? Do PHP devs only use for loops, `strpos()`, `explode()`, or `preg_match()`??

**Comment by visitek** [comment]
Hi. We are using this lib... You've done an amazing job. But the license is missing while we have it in composer dependency.
